version: '3.8'

services:
  ecomrevisited:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__EcomConnectionString=Server=sqlserver;Database=EcomDb;User Id=SA;Password=Testing6969;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Testing6969"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
